---
# tasks file for ephemeral.minecraft_common
- name: Get total memory
  shell: free --mega -w | grep Mem | awk '{ print $2 }'
  register: var_total_memory
- name: Install JRE
  apt:
    update_cache: true
    pkg:
    - openjdk-8-jre-headless
    - unzip
- name: Install vanilla 1.16.4
  import_tasks: ./vanilla-1.16.4.yml
  when: server_type == 'vanilla-1.16.4'
- name: Install FTB revelation 3.4.0
  import_tasks: ./ftb-revelation-3.4.0.yml
  when: server_type == 'ftb-revelation-3.4.0'
- name: Install SkyFactory 4
  import_tasks: ./skyfactory-4.yml
  when: server_type == 'skyfactory-4.2.2'
- name: debug output
  debug:
    msg: "{{ launch_command }}"

- name: Generate minecraft systemd service
  template:
    src: mc-server.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Start minecraft service
  systemd:
    name: mc-server
    state: started
    enabled: no
    daemon_reload: yes
