---
# tasks file for ephemeral.minecraft_common
- name: Install JRE
  apt:
    update_cache: true
    pkg:
    - openjdk-8-jre-headless
- name: Install vanilla latest
  import_tasks: ./vanilla-latest.yml
  when: server_type == 'vanilla-latest'
- name: Generate minecraft systemd service
  template:
    src: mc-server.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Start minecraft service
  systemd:
    name: mc-server
    state: started
    enabled: yes
