---
# tasks file for ephemeral.formatdisk
- name: Get disk format status
  shell: "file -s {{ device }}"
  register: var_disk_format
  # If unformatted,
  # /dev/xvdf: data
  # If formatted,
  # /dev/xvda1: SGI XFS filesystem data (blksz 4096, inosz 512, v2 dirs)

- name: Format disk as ext4 if unformatted
  when: "var_disk_format.stdout == device + ': data'"
  community.general.parted:
    device: "{{ device }}"
    number: 1
    state: present
    fs_type: ext4

- name: Format partition
  community.general.filesystem:
    dev: "{{ device }}{% if 'nvme' not in device %}1{% else %}p1{% endif %}"
    fstype: ext4
    state: present

- name: Make persistent volume folder
  file:
    path: "{{ persistent_mount }}"
    state: directory
    mode: '0755'
    owner: minecraft
    group: minecraft
- name: Mount persistent volume
  ansible.posix.mount:
    src: "{{ device }}{% if 'nvme' not in device %}1{% else %}p1{% endif %}"
    path: "{{ persistent_mount }}"
    state: mounted
    fstype: ext4
    opts: discard,defaults,noatime
