
name: build docker images
on:
  release:
    types:
    - published
  push:
    branches:
    - deployment

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      docker_build_tag: 
    steps: 
    - uses: actions/checkout@v2
    - name: create tag name
      id: tag
      run: echo "::set-output name=tag_name::$(echo '${{ github.ref }}' | awk -F'/' '{ print $3 }')"
    - name: Set up docker builder
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        #platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
        platforms: linux/arm/v7
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jack-michaud/ephemeral-server/ephemeralbot
        push: true
        tags: |
          ephemeralserver/ephbot:latest
          ephemeralserver/ephbot:${{ env.TAG_NAME }}

