
name: build docker images
on:
  release:
    types:
    - published
  push:
    branches:
    - deployment

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      docker_build_tag: 
    steps: 
    - uses: actions/checkout@v2
    - name: Set up docker builder
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jack-michaud/ephemeral-server/ephemeralbot
          tag_with_ref: true

